console.log("Seed file started");
require("dotenv").config();

const mongoose = require("mongoose");
const Service = require("./models/Service");

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("✅ MongoDB Connected"))
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });

const services = [
  {
    name: "Electrician",
    slug: "electrician",
    category: "Home Services",
    description: "Professional electrical repair and installation.",
    price: 500,
    providerName: "Ramesh Kumar",
    phone: "9876543210",
    location: "Hyderabad",
    image: "/images/services/electrician.png",
    rating: 4.8,
  },
  {
    name: "Plumber",
    slug: "plumber",
    category: "Home Services",
    description: "Expert plumbing repair and maintenance.",
    price: 480,
    providerName: "Suresh",
    phone: "9876543211",
    location: "Hyderabad",
    image: "/images/services/plumber.png",
    rating: 4.7,
  },
  {
    name: "Carpenter",
    slug: "carpenter",
    category: "Home Services",
    description: "Furniture repair and wood work.",
    price: 900,
    providerName: "Mahesh",
    phone: "9876543212",
    location: "Hyderabad",
    image: "/images/services/carpenter.png",
    rating: 4.9,
  },
  {
    name: "Painter",
    slug: "painter",
    category: "Home Services",
    description: "Interior and exterior painting.",
    price: 2500,
    providerName: "Kiran",
    phone: "9876543213",
    location: "Hyderabad",
    image: "/images/services/painter.png",
    rating: 4.6,
  },
  {
    name: "AC Repair",
    slug: "ac-repair",
    category: "Appliance",
    description: "AC installation and servicing.",
    price: 1200,
    providerName: "Ravi",
    phone: "9876543214",
    location: "Hyderabad",
    image: "/images/services/ac-repair.png",
    rating: 4.9,
  },
  {
    name: "Refrigerator Repair",
    slug: "refrigerator-repair",
    category: "Appliance",
    description: "Refrigerator repair and maintenance.",
    price: 1000,
    providerName: "Naresh",
    phone: "9876543215",
    location: "Hyderabad",
    image: "/images/services/refrigerator-repair.png",
    rating: 4.8,
  },
  {
    name: "Washing Machine Repair",
    slug: "washing-machine-repair",
    category: "Appliance",
    description: "Repair for all washing machine brands.",
    price: 900,
    providerName: "Ganesh",
    phone: "9876543216",
    location: "Hyderabad",
    image: "/images/services/washing-machine-repair.png",
    rating: 4.7,
  },
  {
    name: "RO Water Purifier",
    slug: "ro-water-purifier",
    category: "Appliance",
    description: "RO installation and servicing.",
    price: 800,
    providerName: "Prakash",
    phone: "9876543217",
    location: "Hyderabad",
    image: "/images/services/water-purifier.png",
    rating: 4.8,
  },
  {
    name: "House Cleaning",
    slug: "house-cleaning",
    category: "Cleaning",
    description: "Complete home deep cleaning service.",
    price: 1500,
    providerName: "Lakshmi",
    phone: "9876543218",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.9,
  },
  {
    name: "Bathroom Cleaning",
    slug: "bathroom-cleaning",
    category: "Cleaning",
    description: "Professional bathroom cleaning.",
    price: 800,
    providerName: "Anitha",
    phone: "9876543219",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  },
  {
    name: "Kitchen Cleaning",
    slug: "kitchen-cleaning",
    category: "Cleaning",
    description: "Complete kitchen cleaning service.",
    price: 1000,
    providerName: "Sowmya",
    phone: "9876543220",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.7,
  },
  {
    name: "Sofa Cleaning",
    slug: "sofa-cleaning",
    category: "Cleaning",
    description: "Professional sofa shampoo cleaning.",
    price: 1200,
    providerName: "Deepak",
    phone: "9876543221",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  },
  {
    name: "Pest Control",
    slug: "pest-control",
    category: "Cleaning",
    description: "Complete pest control service.",
    price: 1800,
    providerName: "Ajay",
    phone: "9876543222",
    location: "Hyderabad",
    image: "/images/services/pest-control.png",
    rating: 4.9,
  },
    {
    name: "Car Wash",
    slug: "car-wash",
    category: "Vehicle",
    description: "Professional doorstep car wash.",
    price: 600,
    providerName: "Vijay",
    phone: "9876543223",
    location: "Hyderabad",
    image: "/images/services/car-wash.png",
    rating: 4.6,
  },
  {
    name: "Bike Service",
    slug: "bike-service",
    category: "Vehicle",
    description: "Complete bike servicing and maintenance.",
    price: 800,
    providerName: "Arun",
    phone: "9876543224",
    location: "Hyderabad",
    image: "/images/services/bike-mechanic.png",
    rating: 4.8,
  },
  {
    name: "Salon at Home",
    slug: "salon-at-home",
    category: "Beauty",
    description: "Professional salon services at your doorstep.",
    price: 1200,
    providerName: "Priya",
    phone: "9876543225",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.9,
  },
  {
    name: "Spa at Home",
    slug: "spa-at-home",
    category: "Beauty",
    description: "Relaxing spa and massage services.",
    price: 1800,
    providerName: "Divya",
    phone: "9876543226",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  },
  {
    name: "Laptop Repair",
    slug: "laptop-repair",
    category: "Electronics",
    description: "Laptop hardware and software repair.",
    price: 1200,
    providerName: "Sai",
    phone: "9876543227",
    location: "Hyderabad",
    image: "/images/services/computer.png",
    rating: 4.8,
  },
  {
    name: "Desktop Repair",
    slug: "desktop-repair",
    category: "Electronics",
    description: "Desktop repair and upgrades.",
    price: 1500,
    providerName: "Rohit",
    phone: "9876543228",
    location: "Hyderabad",
    image: "/images/services/computer.png",
    rating: 4.7,
  },
  {
    name: "Mobile Repair",
    slug: "mobile-repair",
    category: "Electronics",
    description: "Smartphone repair service.",
    price: 700,
    providerName: "Abhi",
    phone: "9876543229",
    location: "Hyderabad",
    image: "/images/services/mobile-repair.png",
    rating: 4.8,
  },
  {
    name: "CCTV Installation",
    slug: "cctv-installation",
    category: "Security",
    description: "CCTV installation for homes and offices.",
    price: 3500,
    providerName: "Harish",
    phone: "9876543230",
    location: "Hyderabad",
    image: "/images/services/cctv-installation.png",
    rating: 4.9,
  },
  {
    name: "Gardening",
    slug: "gardening",
    category: "Outdoor",
    description: "Garden maintenance and landscaping.",
    price: 900,
    providerName: "Raju",
    phone: "9876543231",
    location: "Hyderabad",
    image: "/images/services/gardening.png",
    rating: 4.7,
  },
  {
    name: "Packers and Movers",
    slug: "packers-and-movers",
    category: "Moving",
    description: "Professional home shifting service.",
    price: 5000,
    providerName: "Krishna",
    phone: "9876543232",
    location: "Hyderabad",
    image: "/images/services/home-shifting.png",
    rating: 4.8,
  },
  {
    name: "Interior Design",
    slug: "interior-design",
    category: "Home Services",
    description: "Modern home interior design solutions.",
    price: 15000,
    providerName: "Pavan",
    phone: "9876543233",
    location: "Hyderabad",
    image: "/images/services/painter.png",
    rating: 4.9,
  },
  {
    name: "Water Tank Cleaning",
    slug: "water-tank-cleaning",
    category: "Cleaning",
    description: "Professional water tank cleaning.",
    price: 2000,
    providerName: "Srinivas",
    phone: "9876543234",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  },
  {
    name: "Home Painting",
    slug: "home-painting",
    category: "Home Services",
    description: "Complete home painting services.",
    price: 8000,
    providerName: "Murali",
    phone: "9876543235",
    location: "Hyderabad",
    image: "/images/services/painter.png",
    rating: 4.9,
  },
    {
    name: "Ceiling Fan Repair",
    slug: "ceiling-fan-repair",
    category: "Electrical",
    description: "Repair and installation of ceiling fans.",
    price: 450,
    providerName: "Kishore",
    phone: "9876543236",
    location: "Hyderabad",
    image: "/images/services/electrician.png",
    rating: 4.7,
  },
  {
    name: "Door Lock Repair",
    slug: "door-lock-repair",
    category: "Security",
    description: "Repair and replacement of door locks.",
    price: 650,
    providerName: "Vinod",
    phone: "9876543237",
    location: "Hyderabad",
    image: "/images/services/locksmith.png",
    rating: 4.8,
  },
  {
    name: "Water Heater Repair",
    slug: "water-heater-repair",
    category: "Appliance",
    description: "Instant and storage geyser repair.",
    price: 850,
    providerName: "Rajesh",
    phone: "9876543238",
    location: "Hyderabad",
    image: "/images/services/water-purifier.png",
    rating: 4.8,
  },
  {
    name: "Microwave Repair",
    slug: "microwave-repair",
    category: "Appliance",
    description: "Microwave oven repair service.",
    price: 950,
    providerName: "Sandeep",
    phone: "9876543239",
    location: "Hyderabad",
    image: "/images/services/computer.png",
    rating: 4.7,
  },
  {
    name: "TV Repair",
    slug: "tv-repair",
    category: "Electronics",
    description: "LED, LCD and Smart TV repair service.",
    price: 1000,
    providerName: "Rakesh",
    phone: "9876543240",
    location: "Hyderabad",
    image: "/images/services/tv-repair.png",
    rating: 4.8,
  },
  {
    name: "Inverter Repair",
    slug: "inverter-repair",
    category: "Electronics",
    description: "Home inverter repair and maintenance.",
    price: 900,
    providerName: "Pradeep",
    phone: "9876543241",
    location: "Hyderabad",
    image: "/images/services/computer.png",
    rating: 4.7,
  },
  {
    name: "Generator Service",
    slug: "generator-service",
    category: "Electrical",
    description: "Generator installation and servicing.",
    price: 2500,
    providerName: "Manoj",
    phone: "9876543242",
    location: "Hyderabad",
    image: "/images/services/mechanic.png",
    rating: 4.8,
  },
  {
    name: "Curtain Cleaning",
    slug: "curtain-cleaning",
    category: "Cleaning",
    description: "Professional curtain cleaning service.",
    price: 850,
    providerName: "Swathi",
    phone: "9876543243",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.9,
  },
  {
    name: "Car Interior Cleaning",
    slug: "car-interior-cleaning",
    category: "Vehicle",
    description: "Complete interior cleaning and detailing.",
    price: 1500,
    providerName: "Ajith",
    phone: "9876543244",
    location: "Hyderabad",
    image: "/images/services/car-wash.png",
    rating: 4.8,
  },
  {
    name: "Bike Washing",
    slug: "bike-washing",
    category: "Vehicle",
    description: "Premium bike washing service.",
    price: 300,
    providerName: "Surya",
    phone: "9876543245",
    location: "Hyderabad",
    image: "/images/services/bike-mechanic.png",
    rating: 4.6,
  },
  {
    name: "Water Leakage Repair",
    slug: "water-leakage-repair",
    category: "Plumbing",
    description: "Quick water leakage repair service.",
    price: 650,
    providerName: "Venkatesh",
    phone: "9876543246",
    location: "Hyderabad",
    image: "/images/services/plumber.png",
    rating: 4.9,
  },
  {
    name: "False Ceiling Work",
    slug: "false-ceiling-work",
    category: "Construction",
    description: "Gypsum and POP false ceiling installation.",
    price: 12000,
    providerName: "Mahender",
    phone: "9876543247",
    location: "Hyderabad",
    image: "/images/services/carpenter.png",
    rating: 4.8,
  },
  {
    name: "Tile Installation",
    slug: "tile-installation",
    category: "Construction",
    description: "Floor and wall tile installation.",
    price: 9500,
    providerName: "Karthik",
    phone: "9876543248",
    location: "Hyderabad",
    image: "/images/services/carpenter.png",
    rating: 4.8,
  },
    {
    name: "Glass Repair",
    slug: "glass-repair",
    category: "Home Services",
    description: "Window and door glass replacement.",
    price: 1200,
    providerName: "Naveen",
    phone: "9876543249",
    location: "Hyderabad",
    image: "/images/services/carpenter.png",
    rating: 4.7,
  },
  {
    name: "CCTV Maintenance",
    slug: "cctv-maintenance",
    category: "Security",
    description: "Annual CCTV maintenance service.",
    price: 1800,
    providerName: "Harsha",
    phone: "9876543250",
    location: "Hyderabad",
    image: "/images/services/cctv-installation.png",
    rating: 4.8,
  },
  {
    name: "Solar Panel Cleaning",
    slug: "solar-panel-cleaning",
    category: "Cleaning",
    description: "Professional solar panel cleaning.",
    price: 1100,
    providerName: "Rohan",
    phone: "9876543251",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.9,
  },
  {
    name: "House Shifting",
    slug: "house-shifting",
    category: "Moving",
    description: "Complete household relocation service.",
    price: 6500,
    providerName: "Sai Movers",
    phone: "9876543252",
    location: "Hyderabad",
    image: "/images/services/home-shifting.png",
    rating: 4.8,
  },
  {
    name: "Office Shifting",
    slug: "office-shifting",
    category: "Moving",
    description: "Office relocation with packing.",
    price: 15000,
    providerName: "Express Movers",
    phone: "9876543253",
    location: "Hyderabad",
    image: "/images/services/home-shifting.png",
    rating: 4.9,
  },
  {
    name: "Wedding Decoration",
    slug: "wedding-decoration",
    category: "Events",
    description: "Complete wedding decoration service.",
    price: 50000,
    providerName: "Dream Events",
    phone: "9876543254",
    location: "Hyderabad",
    image: "/images/services/painter.png",
    rating: 5.0,
  },
  {
    name: "Birthday Decoration",
    slug: "birthday-decoration",
    category: "Events",
    description: "Birthday party decoration.",
    price: 8000,
    providerName: "Celebrations",
    phone: "9876543255",
    location: "Hyderabad",
    image: "/images/services/painter.png",
    rating: 4.8,
  },
  {
    name: "Home Tutor",
    slug: "home-tutor",
    category: "Education",
    description: "Experienced tutors for all subjects.",
    price: 2000,
    providerName: "Tutor Point",
    phone: "9876543256",
    location: "Hyderabad",
    image: "/images/services/computer.png",
    rating: 4.9,
  },
  {
    name: "Yoga Trainer",
    slug: "yoga-trainer",
    category: "Fitness",
    description: "Personal yoga sessions at home.",
    price: 1500,
    providerName: "Yoga Life",
    phone: "9876543257",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  },
  {
    name: "Personal Gym Trainer",
    slug: "personal-gym-trainer",
    category: "Fitness",
    description: "Certified personal fitness trainer.",
    price: 2500,
    providerName: "Fit Coach",
    phone: "9876543258",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.9,
  },
  {
    name: "Pet Grooming",
    slug: "pet-grooming",
    category: "Pets",
    description: "Professional pet grooming at home.",
    price: 1200,
    providerName: "Pet Care",
    phone: "9876543259",
    location: "Hyderabad",
    image: "/images/services/cleaning.png",
    rating: 4.8,
  }
];

async function seedDatabase() {
  try {
    console.log("🚀 Starting database seeding...");

    await Service.deleteMany({});
    console.log("🗑 Existing services deleted.");

    const insertedServices = await Service.insertMany(services);

    console.log(`✅ Successfully inserted ${insertedServices.length} services.`);

    mongoose.connection.close();
    console.log("🔒 MongoDB connection closed.");

    process.exit(0);
  } catch (error) {
    console.error("❌ Error while seeding database:");
    console.error(error);

    mongoose.connection.close();
    process.exit(1);
  }
}

seedDatabase();